community/urls.py
from django.urls import path
from .views import *

app_name = 'community'

urlpatterns = [
    path('', communityMain, name="communityMain"),
    path('<int:post_id>', communityDetail, name="communityDetail"),
    path('<int:post_id>/comment', create_comment, name="comment"),
]

django_temp/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views, urls



urlpatterns = [
    path('', include('main.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path("user/", include("user.urls")),
    path("alcohol/", include("calc_alc.urls")),
    path('community/', include("community.urls")),
    path('todaylog/', include("todaylog.urls")),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('tmp', views.tmp, name='tmp'),
    path('past', views.past, name='past'),
]

todaylog/urls.py
from django.urls import path
from .views import *

app_name = 'todaylog'

urlpatterns = [
    path('todaylog', todaylogMain, name="todaylogMain"),
    path('todaylog/write', todaylogWrite, name="todaylogWrite"),
    path('todaylog/edit', todaylogEdit, name="todaylogEdit"),
    path('todaylog/delete', todaylogDelete, name="todaylogDelete"),
]

community/models.py
from django.db import models

# Create your models here.

community/views.py
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator
from todaylog.models import Todaylog, Comment
from django.contrib.auth.decorators import login_required

def communityMain(request):
    community_list = Todaylog.objects.all() 
    paginator = Paginator(community_list, 4)
    page = request.GET.get('page') 
    posts = paginator.get_page(page) 
    return render(request, 'community/community_main.html', {'posts':posts})

def communityDetail(request, post_id): 
    post = get_object_or_404(Todaylog, pk = post_id) 
    comments = Comment.objects.filter(post_id=post_id, comment_id__isnull=True)
    return render(request, 'community/community_detail.html', {'post':post, 'comments':comments})

@login_required
def create_comment(request, post_id):
    if request.method == 'POST':
        comment = Comment()
        comment.post_id = Todaylog.objects.get(pk=post_id)
        comment.author = request.user
        comment.save()
    return redirect('/community/' + str(post_id))

templates/community/community_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>한잔 해</title>
</head>
<body>
    <form action="" method="POST">
    <div class="community-main">
        <section class="cardViewSection">
            <div class="cardView">
                <h1>커뮤니티</h1>
                <header>
                    <div class="categoryInfo">카테고리->상세종류</div>
                </header>
                <div class="cardImage">
                    <img src="image/image2.jpg" width="250" alt="">
                </div>
                <div class="cardPrice">
                    <a1>가격</a1>
                </div>
                <div class="cardFeed">
                    <a1>피드내용</a1>
                </div>
            </div>

            <div class="cardReview">
                <div class="comment">
                    <form action="">
                        <input type="text" placeholder="댓글 입력..." class="commenttpye"> 
                        <button class="btn btn-lg btn-primary btn-block" type="submit">댓글 입력</button> 
                    </form>
                </div>
            </div>
        </section>
    </div>
    </form>
</body>
</html>

templates/community/community_write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>한잔 해</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <link href="css/community_write.css" rel="stylesheet">
</head>
<body>
    <section>
        <div class="community-write">
            <form action="" method="post">
                <div class="op1">
                <h1>커뮤니티 글 작성</h1><br>
                <div class="shit">
                    <div class="form-check form-switch" style="float: right;">
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault">비공개 설정</label>
                      </div>
                </div><br><br>
                <label for="exampleDataList" class="form-label">카테고리</label>
                    <input class="form-control" list="datalistOptions" id="exampleDataList" placeholder="종류 선택">
                        <datalist id="datalistOptions">
                            <option value="소주">
                            <option value="맥주">
                            <option value="양주">
                            <option value="와인">
                            <option value="막걸리">
                        </datalist>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">상세종류</label>
                    <input type="text" class="form-control" id="detail" placeholder="술의 이름을 적어주세요">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">한줄평가</label>
                    <input type="text" class="form-control" id="review" placeholder="한줄 평가를 적어주세요"> 
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">피드내용</label>
                    <textarea class="form-control" id="feed" rows="3"></textarea>
                </div>
                <div class="write-date">
                    <label for="date">작성날짜</label>
                    <input type="date" class="form-control" id="date" />
                </div>
                <div class="mb-3">
                    <label for="formFileSm" class="form-label">이미지 첨부</label>
                    <input class="form-control form-control-sm" id="formFileSm" type="file">
                </div>
                <br>
                <div class="butn">
                    <button class="submitBtn" type="submit">작성</button>
                </div>
        </div>
            </form>
        </div>
    </section>
</body>
</html>

templates/community/list.html
{% extends '../base/base.html' %}

{% load static %}

{% block title %}
과거의 기록
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static './styles/write.css' %}" type="text/css" />
{% endblock %}


{% block content %}

<div class="write-wrapper">
        <div class="notepad">
            <div class="top"></div>
            <div class="paper" contenteditable="true">
                {% for post in posts %} &nbsp
                {{ post.author }} &nbsp
                {{ post.category }} &nbsp
                {{ post.drink }} &nbsp
                {{ post.rating_content}} <br><br>
                {% endfor %}  

            </div>
          </div>
</div>




{% endblock %}

templates/community/write.html
{% extends '../base/base.html' %}

{% load static %}

{% block title %}
오늘의 기록
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static './styles/write.css' %}" type="text/css" />
{% endblock %}


{% block content %}

<div class="write-wrapper">
    <div id="wrap" class="input">
        <section class="input-content">
          <h2>오늘의 한잠 작성</h2>
          <div class="input-content-wrap">
              
            <form method="POST" action="{% url 'todaylog:todaylogWrite' %}">
                {% csrf_token %}
            <dl class="inputbox">
                <dt class="inputbox-title">술 종류</dt>
                <dd class="inputbox-content">
                  <input name="category" id="category" type="text" required/>
                  <span class="underline"></span>
                </dd>
              </dl>
            <dl class="inputbox">
              <dt class="inputbox-title">술 이름</dt>
              <dd class="inputbox-content">
                <input name="drink" id="drink" type="text" required/>
                <span class="underline"></span>
              </dd>
            </dl>
            <dl class="inputbox">
                <dt class="inputbox-title">한줄평가</dt>
                <dd class="inputbox-content">
                    <input name="rating_content" id="rating_content" type="text" required/>
                    <span class="underline"></span>
                </dd>
              </dl>
            <div class="btns">
                <button class="btn btn-cancel" style="background-color:black;color: #fff;">작성</button>
                <button class="btn btn-cancel" style="background-color:black;color: #fff;">취소</button>
            </div>
            </form>
          </div>
        </section>
      </div>
</div>


{% endblock %}